/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v1alpha1 "github.com/kcp-dev/kcp/sdk/apis/provisioning/v1alpha1"
	provisioningv1alpha1 "github.com/kcp-dev/kcp/sdk/client/applyconfiguration/provisioning/v1alpha1"
	scheme "github.com/kcp-dev/kcp/sdk/client/clientset/versioned/scheme"
)

// WorkspaceRootRequestsGetter has a method to return a WorkspaceRootRequestInterface.
// A group's client should implement this interface.
type WorkspaceRootRequestsGetter interface {
	WorkspaceRootRequests() WorkspaceRootRequestInterface
}

// WorkspaceRootRequestInterface has methods to work with WorkspaceRootRequest resources.
type WorkspaceRootRequestInterface interface {
	Create(ctx context.Context, workspaceRootRequest *v1alpha1.WorkspaceRootRequest, opts v1.CreateOptions) (*v1alpha1.WorkspaceRootRequest, error)
	Update(ctx context.Context, workspaceRootRequest *v1alpha1.WorkspaceRootRequest, opts v1.UpdateOptions) (*v1alpha1.WorkspaceRootRequest, error)
	UpdateStatus(ctx context.Context, workspaceRootRequest *v1alpha1.WorkspaceRootRequest, opts v1.UpdateOptions) (*v1alpha1.WorkspaceRootRequest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.WorkspaceRootRequest, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.WorkspaceRootRequestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkspaceRootRequest, err error)
	Apply(ctx context.Context, workspaceRootRequest *provisioningv1alpha1.WorkspaceRootRequestApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.WorkspaceRootRequest, err error)
	ApplyStatus(ctx context.Context, workspaceRootRequest *provisioningv1alpha1.WorkspaceRootRequestApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.WorkspaceRootRequest, err error)
	WorkspaceRootRequestExpansion
}

// workspaceRootRequests implements WorkspaceRootRequestInterface
type workspaceRootRequests struct {
	client rest.Interface
}

// newWorkspaceRootRequests returns a WorkspaceRootRequests
func newWorkspaceRootRequests(c *ProvisioningV1alpha1Client) *workspaceRootRequests {
	return &workspaceRootRequests{
		client: c.RESTClient(),
	}
}

// Get takes name of the workspaceRootRequest, and returns the corresponding workspaceRootRequest object, and an error if there is any.
func (c *workspaceRootRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WorkspaceRootRequest, err error) {
	result = &v1alpha1.WorkspaceRootRequest{}
	err = c.client.Get().
		Resource("workspacerootrequests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of WorkspaceRootRequests that match those selectors.
func (c *workspaceRootRequests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WorkspaceRootRequestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.WorkspaceRootRequestList{}
	err = c.client.Get().
		Resource("workspacerootrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested workspaceRootRequests.
func (c *workspaceRootRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("workspacerootrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a workspaceRootRequest and creates it.  Returns the server's representation of the workspaceRootRequest, and an error, if there is any.
func (c *workspaceRootRequests) Create(ctx context.Context, workspaceRootRequest *v1alpha1.WorkspaceRootRequest, opts v1.CreateOptions) (result *v1alpha1.WorkspaceRootRequest, err error) {
	result = &v1alpha1.WorkspaceRootRequest{}
	err = c.client.Post().
		Resource("workspacerootrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(workspaceRootRequest).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a workspaceRootRequest and updates it. Returns the server's representation of the workspaceRootRequest, and an error, if there is any.
func (c *workspaceRootRequests) Update(ctx context.Context, workspaceRootRequest *v1alpha1.WorkspaceRootRequest, opts v1.UpdateOptions) (result *v1alpha1.WorkspaceRootRequest, err error) {
	result = &v1alpha1.WorkspaceRootRequest{}
	err = c.client.Put().
		Resource("workspacerootrequests").
		Name(workspaceRootRequest.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(workspaceRootRequest).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *workspaceRootRequests) UpdateStatus(ctx context.Context, workspaceRootRequest *v1alpha1.WorkspaceRootRequest, opts v1.UpdateOptions) (result *v1alpha1.WorkspaceRootRequest, err error) {
	result = &v1alpha1.WorkspaceRootRequest{}
	err = c.client.Put().
		Resource("workspacerootrequests").
		Name(workspaceRootRequest.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(workspaceRootRequest).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the workspaceRootRequest and deletes it. Returns an error if one occurs.
func (c *workspaceRootRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("workspacerootrequests").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *workspaceRootRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("workspacerootrequests").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched workspaceRootRequest.
func (c *workspaceRootRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkspaceRootRequest, err error) {
	result = &v1alpha1.WorkspaceRootRequest{}
	err = c.client.Patch(pt).
		Resource("workspacerootrequests").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied workspaceRootRequest.
func (c *workspaceRootRequests) Apply(ctx context.Context, workspaceRootRequest *provisioningv1alpha1.WorkspaceRootRequestApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.WorkspaceRootRequest, err error) {
	if workspaceRootRequest == nil {
		return nil, fmt.Errorf("workspaceRootRequest provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(workspaceRootRequest)
	if err != nil {
		return nil, err
	}
	name := workspaceRootRequest.Name
	if name == nil {
		return nil, fmt.Errorf("workspaceRootRequest.Name must be provided to Apply")
	}
	result = &v1alpha1.WorkspaceRootRequest{}
	err = c.client.Patch(types.ApplyPatchType).
		Resource("workspacerootrequests").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *workspaceRootRequests) ApplyStatus(ctx context.Context, workspaceRootRequest *provisioningv1alpha1.WorkspaceRootRequestApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.WorkspaceRootRequest, err error) {
	if workspaceRootRequest == nil {
		return nil, fmt.Errorf("workspaceRootRequest provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(workspaceRootRequest)
	if err != nil {
		return nil, err
	}

	name := workspaceRootRequest.Name
	if name == nil {
		return nil, fmt.Errorf("workspaceRootRequest.Name must be provided to Apply")
	}

	result = &v1alpha1.WorkspaceRootRequest{}
	err = c.client.Patch(types.ApplyPatchType).
		Resource("workspacerootrequests").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
