//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"

	provisioningv1alpha1 "github.com/kcp-dev/kcp/sdk/apis/provisioning/v1alpha1"
	provisioningv1alpha1client "github.com/kcp-dev/kcp/sdk/client/clientset/versioned/typed/provisioning/v1alpha1"
)

// WorkspaceRootRequestsClusterGetter has a method to return a WorkspaceRootRequestClusterInterface.
// A group's cluster client should implement this interface.
type WorkspaceRootRequestsClusterGetter interface {
	WorkspaceRootRequests() WorkspaceRootRequestClusterInterface
}

// WorkspaceRootRequestClusterInterface can operate on WorkspaceRootRequests across all clusters,
// or scope down to one cluster and return a provisioningv1alpha1client.WorkspaceRootRequestInterface.
type WorkspaceRootRequestClusterInterface interface {
	Cluster(logicalcluster.Path) provisioningv1alpha1client.WorkspaceRootRequestInterface
	List(ctx context.Context, opts metav1.ListOptions) (*provisioningv1alpha1.WorkspaceRootRequestList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type workspaceRootRequestsClusterInterface struct {
	clientCache kcpclient.Cache[*provisioningv1alpha1client.ProvisioningV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *workspaceRootRequestsClusterInterface) Cluster(clusterPath logicalcluster.Path) provisioningv1alpha1client.WorkspaceRootRequestInterface {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return c.clientCache.ClusterOrDie(clusterPath).WorkspaceRootRequests()
}

// List returns the entire collection of all WorkspaceRootRequests across all clusters.
func (c *workspaceRootRequestsClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*provisioningv1alpha1.WorkspaceRootRequestList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).WorkspaceRootRequests().List(ctx, opts)
}

// Watch begins to watch all WorkspaceRootRequests across all clusters.
func (c *workspaceRootRequestsClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).WorkspaceRootRequests().Watch(ctx, opts)
}
