name: Build and Publish KCP Image

permissions:
  packages: write

on:
  push:
    branches:
      - main
      - 'release-*'
    tags:
    - 'v*'

jobs:
  build:
    name: Build KCP Image
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ env.sha_short }}
    strategy:
      matrix:
        platforms:
        - linux/amd64
        - linux/arm64
        - linux/ppc64le
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: v1.19

      - name: Get the short sha
        id: vars
        run: |
          echo "sha_short=$(echo ${{ github.sha }} | cut -b -7)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/kcp
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=${{ env.sha_short }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push ${{ matrix.platform }}
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.platform }}
          cache-from: type=gha,scope=$GITHUB_REF_NAME-{{ matrix.platform }}
          cache-to: type=gha,scope=$GITHUB_REF_NAME-{{ matrix.platform }},mode=max

